"""Central configuration for EnzySelect.

Single source of truth for disclaimers, schema, scoring defaults and the chart
palette, so that wording and numbers cannot drift between modules.

EnzySelect is an educational prototype. Nothing in this package is a validated
scientific model.
"""

from __future__ import annotations

from pathlib import Path

# --------------------------------------------------------------------------
# Paths
# --------------------------------------------------------------------------
PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = PROJECT_ROOT / "data"
CANDIDATES_CSV = DATA_DIR / "candidates.csv"
REFERENCES_CSV = DATA_DIR / "structure_references.csv"

RANDOM_SEED = 20260807
N_CANDIDATES = 50

# --------------------------------------------------------------------------
# Disclaimers — reused verbatim across the UI and the README
# --------------------------------------------------------------------------
HEADLINE_DISCLAIMER = (
    "**Educational prototype — demonstration only.** EnzySelect is not a "
    "validated scientific, medical, environmental or industrial "
    "decision-making system. All candidate performance values are synthetic "
    "and illustrative. Every output is a prioritization signal that requires "
    "experimental validation."
)

SCIENTIFIC_INTEGRITY_NOTES = [
    "AlphaFold structure predictions do not establish enzyme activity. A "
    "predicted fold is a structural hypothesis, not evidence of catalysis.",
    "pLDDT measures the model's confidence in predicted local structure. It "
    "is not a measure of thermal stability, catalytic performance, "
    "expression yield or industrial suitability.",
    "The degradation-rate values in this demo are synthetic. They were "
    "generated by a random process and describe no real enzyme.",
    "Experimental validation in a laboratory would be required before any "
    "production, procurement or investment decision.",
    "This application provides no regulatory, medical, environmental or "
    "safety approval of any kind.",
    "Nothing here demonstrates that any enzyme can safely degrade plastic "
    "under real-world conditions.",
]

SCORE_CAVEAT = (
    "The overall score is a transparent weighted decision-support heuristic "
    "chosen by the user, not a validated biological model. Changing the "
    "weights changes the ranking; that sensitivity is the point of the tool, "
    "and it is also its main limitation."
)

STRUCTURE_LINK_CAVEAT = (
    "Structure links point to a **real, verifiable AlphaFold DB entry for a "
    "characterized representative of the candidate's structural family**. "
    "They are *not* structures of the synthetic candidate, which does not "
    "exist. Real reference metadata and synthetic candidate estimates are "
    "kept in separate columns throughout."
)

SYNTHETIC_DATA_NOTICE = (
    "Rows in `candidates.csv` describe **synthetic candidates that do not "
    "exist**. They carry no UniProt accession. Only the family-reference "
    "columns contain real, API-verified metadata."
)

# Vocabulary discipline: terms the UI must never use, and their replacements.
# Enforced by tests/test_language.py so the wording cannot regress.
BANNED_TERMS = [
    "proven enzyme",
    "guaranteed degradation",
    "validated industrial performance",
    "commercially ready",
    "safe for deployment",
]

# --------------------------------------------------------------------------
# Structural families
#
# Each synthetic candidate belongs to a structural family anchored to a REAL
# enzyme whose UniProt accession was verified against the UniProt REST API on
# 2026-08-07. The anchor supplies a verifiable structure link and realistic
# ranges for sequence length and temperature optimum. No performance claim is
# ever attached to the real enzyme.
# --------------------------------------------------------------------------
STRUCTURE_FAMILIES = {
    "PETase-like": {
        "code": "PETL",
        "uniprot": "A0A0K8P6T7",
        # Filled from the UniProt API at generation time; these are fallbacks.
        "ref_name": "Poly(ethylene terephthalate) hydrolase",
        "ref_organism": "Piscinibacter sakaiensis",
        "ref_length": 290,
        "temp_mu": 46.0,
        "ph_mu": 8.4,
        "len_mu": 290,
        "len_sd": 22,
        "rate_shift": 0.35,  # log10 units applied to the synthetic rate
        "share": 0.26,
    },
    "Leaf-branch-compost-cutinase-like": {
        "code": "LCCL",
        "uniprot": "G9BY57",
        "ref_name": "Leaf-branch compost cutinase",
        "ref_organism": "Unknown prokaryotic organism",
        "ref_length": 293,
        "temp_mu": 70.0,
        "ph_mu": 8.2,
        "len_mu": 293,
        "len_sd": 18,
        "rate_shift": 0.45,
        "share": 0.24,
    },
    "Thermobifida-cutinase-like": {
        "code": "TFCL",
        "uniprot": "Q6A0I4",
        "ref_name": "Cutinase cut2",
        "ref_organism": "Thermobifida fusca",
        "ref_length": 301,
        "temp_mu": 63.0,
        "ph_mu": 8.0,
        "len_mu": 285,
        "len_sd": 20,
        "rate_shift": 0.15,
        "share": 0.22,
    },
    "Fungal-cutinase-like": {
        "code": "FUNC",
        "uniprot": "P00590",
        "ref_name": "Cutinase 1",
        "ref_organism": "Fusarium vanettenii",
        "ref_length": 230,
        "temp_mu": 41.0,
        "ph_mu": 8.6,
        "len_mu": 232,
        "len_sd": 16,
        "rate_shift": -0.15,
        "share": 0.16,
    },
    # Acts downstream on MHET rather than on PET itself: deliberately given a
    # low direct PET rate so the ranking has a real trade-off to expose.
    "MHET-hydrolase-like": {
        "code": "MHTL",
        "uniprot": "A0A0K8P8E7",
        "ref_name": "Mono(2-hydroxyethyl) terephthalate hydrolase",
        "ref_organism": "Piscinibacter sakaiensis",
        "ref_length": 603,
        "temp_mu": 40.0,
        "ph_mu": 7.6,
        "len_mu": 590,
        "len_sd": 30,
        "rate_shift": -0.75,
        "share": 0.12,
    },
}

ALPHAFOLD_ENTRY_URL = "https://alphafold.ebi.ac.uk/entry/{acc}"
ALPHAFOLD_API_URL = "https://alphafold.ebi.ac.uk/api/prediction/{acc}"
UNIPROT_API_URL = "https://rest.uniprot.org/uniprotkb/{acc}.json"

# Simulated sampling environments. These are provenance labels for a synthetic
# metagenomic screen, not species-level claims about real organisms.
SOURCE_ENVIRONMENTS = {
    "compost metagenome (simulated)": {"temp_shift": 6.0, "salt_mu": 12.0, "share": 0.26},
    "hot-spring metagenome (simulated)": {"temp_shift": 12.0, "salt_mu": 9.0, "share": 0.16},
    "marine-sediment metagenome (simulated)": {"temp_shift": -4.0, "salt_mu": 78.0, "share": 0.22},
    "wastewater-sludge metagenome (simulated)": {"temp_shift": -1.0, "salt_mu": 22.0, "share": 0.20},
    "soil metagenome (simulated)": {"temp_shift": -3.0, "salt_mu": 14.0, "share": 0.16},
}

EVIDENCE_LEVELS = {
    0: "No supporting record (in-silico only)",
    1: "Single simulated observation",
    2: "Simulated replicate observations",
    3: "Simulated multi-condition dataset",
    4: "Simulated cross-laboratory dataset",
}

EXPERIMENTAL_STATUSES = [
    "in_silico_only",
    "expressed_in_vitro",
    "activity_screened",
    "pilot_evaluated",
]

# --------------------------------------------------------------------------
# Scoring defaults
# --------------------------------------------------------------------------
DEFAULT_WEIGHTS = {
    "process_fit": 0.30,
    "performance": 0.25,
    "catalytic_confidence": 0.15,
    "structural_confidence": 0.10,
    "feasibility": 0.10,
    "evidence": 0.10,
}

COMPONENT_LABELS = {
    "process_fit": "Process-condition fit",
    "performance": "Synthetic degradation performance",
    "catalytic_confidence": "Catalytic-site confidence",
    "structural_confidence": "Structural confidence (pLDDT)",
    "feasibility": "Production feasibility",
    "evidence": "Evidence level (synthetic)",
}

# Sub-weights inside the process-fit component.
DEFAULT_PROCESS_SUBWEIGHTS = {
    "temperature": 0.45,
    "ph": 0.35,
    "salinity": 0.20,
}

# Tolerance = the distance from the target at which fit falls to ~0.61.
DEFAULT_TOLERANCES = {
    "temperature_c": 8.0,
    "ph": 1.0,
}

# pLDDT below this is treated as no structural confidence; AlphaFold's own
# guidance calls <50 a likely-disordered / low-confidence region.
PLDDT_FLOOR = 50.0

PRIORITY_BANDS = [
    (70.0, "Prioritize for testing"),
    (50.0, "Secondary queue"),
    (0.0, "Deprioritize for now"),
]

DEFAULT_CONDITIONS = {
    "temperature_c": 65.0,
    "ph": 8.0,
    "salinity_g_per_l": 20.0,
}

DEFAULT_ECONOMICS = {
    "cost_per_test_eur": 4200.0,
    "pool_size": N_CANDIDATES,
    "weeks_per_cycle": 3.0,
    "tests_per_cycle": 8,
    "budget_eur": 60000.0,
    "max_candidates": 8,
}

# --------------------------------------------------------------------------
# Chart palette
#
# Taken unchanged from the validated default palette and confirmed with the
# palette validator against the light chart surface #fcfcfb:
#   - 6 categorical slots, adjacent pairs: ALL CHECKS PASS (contrast WARN on
#     aqua/yellow/magenta -> relief rule applied: direct labels + table view)
#   - 2 slots (blue, orange), all pairs: ALL CHECKS PASS
#   - diverging poles (blue, red), all pairs: ALL CHECKS PASS
# The app pins Streamlit to the light theme (.streamlit/config.toml) so the
# surface the validator checked is the surface actually rendered.
# --------------------------------------------------------------------------
PALETTE = {
    "series": [
        "#2a78d6",  # 1 blue
        "#eb6834",  # 2 orange
        "#1baf7a",  # 3 aqua
        "#eda100",  # 4 yellow
        "#e87ba4",  # 5 magenta
        "#008300",  # 6 green
    ],
    "surface": "#fcfcfb",
    "page": "#f9f9f7",
    "text_primary": "#0b0b0b",
    "text_secondary": "#52514e",
    "muted": "#898781",
    "grid": "#e1e0d9",
    "axis": "#c3c2b7",
    "up": "#2a78d6",     # diverging pole: improved rank
    "down": "#e34948",   # diverging pole: worsened rank
    "flat": "#898781",   # neutral midpoint
    # Single-hue sequential ramp (blue, light -> dark) for score magnitude.
    "sequential": ["#cde2fb", "#9ec5f4", "#6da7ec", "#3987e5", "#256abf", "#184f95"],
}

# Component -> categorical slot. Fixed assignment: colour follows the
# component, never its rank or its current value.
COMPONENT_COLORS = {
    key: PALETTE["series"][i] for i, key in enumerate(DEFAULT_WEIGHTS)
}

PLOTLY_FONT = 'system-ui, -apple-system, "Segoe UI", sans-serif'
